### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by lebull** [SundayServiceVR/sunday-service-vr#27]
Lets get some unit testing rolling.  If you pick this issue up, feel free to only do a portion of it, just make sure to comment what parts your tests will encompass

**Comment by icedog225** [comment]
Going to pick this up and start working on some basic tests. Starting out by trying to make sure all of the basic scheduling tasks remain functional and present the correct data & format. Will also try and set up some GitHub actions to test on pull requests.

**Comment by icedog225** [comment]
The PR for this will just provide a few simple tests:

* Smoke test (i.e. is the app rendering at all lol)
* Paste generation (do discord, social media, and whiteboard pastes generate correctly)

Other areas of the are currently in flux a bit, so I decided not to test them for now until things are a bit more solidified. Ideally I don't want to introduce brittle tests that need to be refactored repeatedly.
