### ISSUE TITLE
Logout confirmation

### ISSUE THREAD

**Issue by icedog225** [SundayServiceVR/sunday-service-vr#28]
At the moment, when you click through the tabs at the top of the page it's very easy to accidentally log yourself out. Would be good to have a confirmation modal to make sure you actually want to log out - as well as possibly moving the logout button towards the right of the screen somewhere so it doesnt seem like a tab.

**Comment by lebull** [comment]
Usually, you see this right aligned and in a dropdown menu, and nothing is preventing from us doing that.  It puts extra clicks between you and accidentally logging out, and there IS some user info that we can place there as well, even if it's super sparse.

**Comment by lebull** [comment]
Also, we can provide a link to reset password there.

**Comment by klAvAx** [comment]
PR #79
