### ISSUE TITLE
Add toast on successful event creation

### ISSUE THREAD

**Issue by icedog225** [SundayServiceVR/sunday-service-vr#38]
At the moment when you create a new event, it isn't immediately clear that anything is changed because the UI doesn't change significantly. Would be good to pop up a 'Success' [toast](https://react-bootstrap.netlify.app/docs/components/toasts/).

**Comment by lebull** [comment]
Would it be better to redirect that form to the "event lineup" page instead?

**Comment by icedog225** [comment]
Could be, yea. As long as something happens that makes it clear that something happened

**Comment by icedog225** [comment]
Closing because #81 addresses this by adding another section to the bottom of the page (for posting signup sheet in discord)
