### ISSUE TITLE
Improve: First setup guide

### ISSUE THREAD

**Issue by klAvAx** [SundayServiceVR/sunday-service-vr#52]
First setup guide i feel needs a lil improvement

What exactly?
- Firebase auth (oriented to beans who had little to no firebase run-ins, me being one for example)
- is ```cd functions``` then ```npm install``` missing? (this could be done via webapp postinstall or preinstall)

**Comment by lebull** [comment]
Thanks a ton!  Here's a PR for that, does this look good?

https://github.com/SundayServiceVR/sunday-service-vr/pull/53

**Comment by klAvAx** [comment]
Yep, looks sweet as far as i can tell! 💯

**Comment by klAvAx** [comment]
Forgor to assign a project to this issue 😅
