### ISSUE TITLE
Bug: "Helpful Links" Should open new tabs.

### ISSUE THREAD

**Issue by lebull** [SundayServiceVR/sunday-service-vr#55]
On the home page

Bonus:
Remove cards for "Performer Interest Sheet" and "Streaming Assets"

Then, in the "S4 Drive Folder" card's body, make a list and add links to those documents explicitly.

* Signup Sheet
  * https://docs.google.com/spreadsheets/d/1ANiFOmz1_ADaMxCtcQE0HdGq3TsJM__Whg87DDN_y9Q/edit?usp=drive_link
* Performer Stream Links
  * https://docs.google.com/spreadsheets/d/1nsAQAiOsuZQcpBBg44SZ8jUvFtXI6WNKE8-WSo9_kiE/edit?usp=drive_link
* Performer Tracking Sheet
  * https://docs.google.com/spreadsheets/d/1x3o6jmxjimZzlY7kRNVyiCG-A5yQ2XHvQlokeeJd8iI/edit?usp=drive_link

**Comment by klAvAx** [comment]
PR #78
