### ISSUE TITLE
Better Firebase Typing

### ISSUE THREAD

**Issue by lebull** [SundayServiceVR/sunday-service-vr#59]
Right now, there's methods like "docToEvent" to convert a firebase document to a strongly typed object.  It looks like we probably should be using something like this: 

https://react-query-firebase.invertase.dev/firestore/typescript
https://firebase.google.com/docs/reference/node/firebase.firestore.FirestoreDataConverter

We also should figure out if we need to swap from native Date objects to firebase's timestamp.

**Comment by lebull** [comment]
As of right now, what we have seems to be working "alright", so we can probably just hold off on doing this unless we run into issues or see a real benefit to doing it the 100% "right" way

**Comment by atomicpeach** [comment]
So I was playing around with this when working on the DJ auth and I think just creating the interface/type and some custom CRUD functions suffices. I'm not a fan of the converter, tbh, but I'm also very much used to relational db models and controllers.

**Comment by lebull** [comment]
I agree.  We can change our minds later if there's a reason to.
