### ISSUE TITLE
Dev: Add Precommit hook for linting

### ISSUE THREAD

**Issue by lebull** [SundayServiceVR/sunday-service-vr#62]
We can add a precommit hook for linting.

https://github.com/typicode/husky

https://typicode.github.io/husky/how-to.html#startup-files

**Comment by atomicpeach** [comment]
We can tie in prettier as well here. I usually have both lint fix and prettier write for the team projects I manage. Just lemme know and I'll hook it up for us~

**Comment by atomicpeach** [comment]
Sidelined for now because we don't want automated code changes at the moment (per discussion in discord).
