### ISSUE TITLE
Generate Discord DJ tentative schedule text

### ISSUE THREAD

**Issue by icedog225** [SundayServiceVR/sunday-service-vr#66]
Each week, the hosts create and post a temporary schedule to confirm set times with the DJs. This step isn't represented in the event scheduler yet. 

Right now hosts can grab bits and pieces from the Discord announcement text, but it would be easier to handle if it were represented as its own tab in the scheduling page.

The generation for this would be very similar to the discord event announcements.

**Comment by lebull** [comment]
I'd also love something similar for opening up the apps as well.  Even if the message isn't really important (we may not even need one), I think it's nice to have a link to the channel along with a reminder of which role to tag.

Maybe we can add this bit underneath our basic event details.
