### ISSUE TITLE
Login with Discord

### ISSUE THREAD

**Issue by lebull** [SundayServiceVR/sunday-service-vr#68]
Thinking through all of the discord things, I think we should be able to copy this project over to our own functions and stand up a standard discord auth flow.

https://github.com/luizkc/firebase-discord-oauth2-example

If we tie into firebase auth's system, we need to make doubly sure to set up roles correctly and make sure dj's don't have access to any data other than their own dj record and any submissions they make.

Really, the most important thing we need from this is the discord user id.

**Comment by mdemong** [comment]
This might be a duplicate / overlap with #64

**Comment by lebull** [comment]
Straight up is!  Thanks!
